name: Update M3U Playlist
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Bu satırları ekleyerek izni garantiye alıyoruz
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
      - name: Run scraping script
        run: python scraper.py
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add custom_playlist.m3u
          git commit -m "Auto Update" || exit 0
          git push origin main
